/* tslint:disable */
/* eslint-disable */
/**
 * MX Platform API
 * The MX Platform API is a powerful, fully-featured API designed to make aggregating and enhancing financial data easy and reliable. It can seamlessly connect your app or website to tens of thousands of financial institutions.  ## What\'s Changed?  Several endpoints, headers, and fields changed in `v20250224`. For more on breaking changes, refer to our [versioning](https://docs.mx.com/api-reference/platform-api/overview/versioning#v20250224) and [migration](https://docs.mx.com/api-reference/platform-api/overview/migration) guides.  ## Version Header Versions are set in the `Accept-Version` header of API requests. Version numbers correspond with the date associated with that version.  The example below uses the version `v20250224`.  ``` -H \'Accept: application/json\' -H \'Accept-Version: v20250224\' ```  --- 
 *
 * The version of the OpenAPI document: 20250224
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export * from "./api";
export * from "./configuration";

